name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@e1c2bf0c8d7813a3243dc649b6af178262a834e9
        with:
          # ssh remote host
          host: ${{ secrets.REMOTE_HOST }}
          # ssh remote port
          port: ${{ secrets.REMOTE_PORT }}
          # ssh remote user
          user: ${{ secrets.REMOTE_USER }}
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.REMOTE_PRIVATE_SSH_KEY }}
          # execute pre-commands before scp
          first_ssh: |
            pm2 stop all
            export TIME=$(date +%s)
            mkdir ~/discord-bot-bak$TIME
            mv /discord-bot/* ~/discord-bot-bak$TIME/*
          # scp from local to remote
          scp: ./* => /discord-bot/
          # execute post-commands after scp
          last_ssh: |
            pm2 start index.js
            pm2 save
