name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@e1c2bf0c8d7813a3243dc649b6af178262a834e9
        with:
          # ssh remote host
          host: ${{ secrets.REMOTE_HOST }}
          # ssh remote port
          port: ${{ secrets.REMOTE_PORT }}
          # ssh remote user
          user: ${{ secrets.REMOTE_USER }}
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.REMOTE_PRIVATE_SSH_KEY }}
          # execute pre-commands before scp
          first_ssh: |
            pm2 stop all
            rm -rf /discord-bot
          # scp from local to remote
          scp: ./* => /discord-bot/
          # execute post-commands after scp
          last_ssh: |
            cd /discord-bot/
            npm install 
            pm2 start index.js
            pm2 save
